_target_: framework.model.losses.compute_vqvae_pred.ComputeLosses

# Latent loss
lmd_latent: 1
latent_manifold: ${.lmd_latent}
latent_manifold_func: ${model.func_recons}

# Reconstruction losses
lmd_exp_recons: 0.15        # expression parameters
recons_exp: ${.lmd_exp_recons}
recons_exp_func: ${model.func_recons}

lmd_jaw_recons: 0.1         # jaw parameters
recons_jaw: ${.lmd_jaw_recons}
recons_jaw_func: ${model.func_recons}

lmd_exp_vel: 0.1
vel_exp: ${.lmd_exp_vel}
vel_exp_func:
  _target_: framework.model.losses.temporal_losses.VelocityLoss

lmd_jaw_vel: 0.05
vel_jaw: ${.lmd_jaw_vel}
vel_jaw_func:
  _target_: framework.model.losses.temporal_losses.VelocityLoss

lmd_exp_acc: 0.1
acc_exp: ${.lmd_exp_acc}
acc_exp_func:
  _target_: framework.model.losses.temporal_losses.AccelerationLoss

lmd_jaw_acc: 0.02
acc_jaw: ${.lmd_jaw_acc}
acc_jaw_func:
  _target_: framework.model.losses.temporal_losses.AccelerationLoss